<?php

/*
 * Menu Structure
 * "Name" => [
 *      Route::Tag
 * ]
 */
$aConfig['MODULE']['Foo']['Menu'] = [

    // Name
    'frontend' => [
        'user',
        'imprint',
        'privacyPolicy',
        'info',
        'PullDown Menu' => [ # Array key names can also be freely assigned and do not need to correspond to an existing tag
             'info',
             'user',
             'imprint',
             'privacyPolicy',
        ],
    ],
];
