#!/usr/bin/env php
<?php
//
///**
// * @experimental
// * @usage php _emvicy
// */
//
//use MVC\Config;
//
//putenv('emvicy=1');
//
//require_once realpath(__DIR__) . '/application/init/util/loader.php';
//
//$oSymfonyComponentConsoleApplication = new \Symfony\Component\Console\Application();
//
////var_dump($_SERVER);exit();
//
//
////$application->register('version')
////    ->addArgument('username', \Symfony\Component\Console\Input\InputArgument::REQUIRED)
////    ->setCode(function (\Symfony\Component\Console\Input\InputInterface $oInputInterface, \Symfony\Component\Console\Output\OutputInterface $oOutputInterface): int {
////
////        dump(
////            $oInputInterface->getArgument('username')
////        );
//////        dump($output);
////
////        return \Symfony\Component\Console\Command\Command::SUCCESS;
////    });
////
////$application->run();
//
//$oSymfonyComponentConsoleApplication
//    ->register('version')
//    ->setAliases(['v'])
//    ->setDescription('displays Emvicy version')
//    ->setCode(function (\Symfony\Component\Console\Input\InputInterface $oInputInterface, \Symfony\Component\Console\Output\OutputInterface $oOutputInterface): int {
//        echo Config::get_MVC_VERSION();
//        nl();
//        return \Symfony\Component\Console\Command\Command::SUCCESS;
//    });
//
//$oSymfonyComponentConsoleApplication
//    ->register('serve')
//    ->setAliases(['s'])
//    ->setDescription("provides a local php server")
//    ->setCode(function (\Symfony\Component\Console\Input\InputInterface $oInputInterface, \Symfony\Component\Console\Output\OutputInterface $oOutputInterface): int {
//        $sCmd = PHP_BINARY . " -S " . Config::get_MVC_PHP_SERVER() . " -t " . \MVC\Config::get_MVC_WEB_ROOT() . '/public/';
//        echo $sCmd;
//        hr();
//        \Emvicy\Emvicy::shellExecute($sCmd);
//        return \Symfony\Component\Console\Command\Command::SUCCESS;
//    });
//
//#--------------------------------------------
//
//$oSymfonyComponentConsoleApplication->run();