#!/usr/bin/env php
<?php

/**
 * run this script on cli
 * @usage php emvicy
 */
putenv('emvicy=1');
require_once realpath(__DIR__) . '/application/init/util/loader.php';
$oEmvicy = \Emvicy\Emvicy::init();
