#!/usr/bin/env php
<?php

/**
 * run this script on cli
 * @usage php emvicy
 * @package Emvicy
 * @copyright ueffing.net
 * @author Guido K.B.W. Üffing <info@ueffing.net>
 * @license GNU GENERAL PUBLIC LICENSE Version 3. See application/doc/COPYING
 */
putenv('emvicy=1');
require './application/init/util/bootstrap.php';
require './application/library/Emvicy/_Emvicy.php';
