<?php

/*
 * modify this Datatype `DTRoutingAdditional` to your needs in:
 *      `modules/{module}/etc/config/{module}/config/_dataType.php`
 * create the Datatype class finally on cli:
 *      `php emvicy datatype`
 */


// template
$oDTRoutingAdditional = \{module}\DataType\DTRoutingAdditional::create()
    ->set_sTitle('{module}')

    # main
    ->set_sTemplate('Frontend/content/index.tpl')

//    ->set_sContent('Frontend/content/index.tpl')
//    ->set_sMainmenu('Frontend/layout/menu.tpl')
//    ->set_sHeader('Frontend/layout/header.tpl')
//    ->set_sNoscript('Frontend/content/_noscript.tpl')
//    ->set_sCookieConsent('Frontend/content/_cookieConsent.tpl')
//    ->set_s{module}ter('Frontend/layout/{module}ter.tpl')

    ->set_aStyle(array (
        '/Emvicy/assets/bootstrap-5.3.3-dist/css/bootstrap.min.css',
        '/Emvicy/assets/fontawesome-free-6.7.2-web/css/all.min.css',
        '/Emvicy/styles/Emvicy.min.css',
    ))
    ->set_aScript(array (
        '/Emvicy/assets/jquery-3.7.1/jquery-3.7.1.min.js',
        '/Emvicy/assets/jquery-cookie-1.4.1/jquery.cookie.min.js',
        '/Emvicy/assets/popper-v2.11.8/popper.min.js',
        '/Emvicy/assets/bootstrap-5.3.3-dist/js/bootstrap.min.js',
        '/Emvicy/scripts/cookieConsent.min.js',
    ));

/*
 * Routes
 */
\MVC\Route::get(
    sPath: '/',
    sClassMethod: '\{module}\Controller\Index::index',
    mOptional: clone $oDTRoutingAdditional->set_sTitle('Home')->set_sTemplate('Frontend/content/index.tpl'),
    sTag: 'home',
);

# array
\MVC\Route::get(
    sPath: '/imprint/',
    sClassMethod: '\{module}\Controller\Index::index',
    mOptional: clone $oDTRoutingAdditional->set_sTitle('Imprint')->set_sTemplate('Frontend/content/imprint.tpl'),
    sTag: 'imprint',
);
# array
\MVC\Route::get(
    sPath: '/privacy-policy/',
    sClassMethod: '\{module}\Controller\Index::index',
    mOptional: clone $oDTRoutingAdditional->set_sTitle('Privacy Policy')->set_sTemplate('Frontend/content/privacy-policy.tpl'),
    sTag: 'privacyPolicy',
);
# array
\MVC\Route::get(
    sPath: '/info/',
    sClassMethod: '\{module}\Controller\Index::phpinfo',
    mOptional: clone $oDTRoutingAdditional->set_sTitle('phpinfo()')->set_sTemplate('Frontend/content/info.tpl'),
    sTag: 'info',
);

#-----------------------------------------------------------------------------------------------------------------------

/*
 * Redirects
 */
$aRedirect = array(
    '/impressum/' => array('sLocation' => '/imprint/', 'iResponseCode' => 301),
);

if (true === isset($aRedirect[\MVC\Request::in()->get_path()]))
{
    \MVC\RequestHelper::redirect(
        sLocation: $aRedirect[\MVC\Request::in()->get_path()]['sLocation'],
        bReplace: ($aRedirect[\MVC\Request::in()->get_path()]['bReplace'] ?? true),
        iResponseCode: ($aRedirect[\MVC\Request::in()->get_path()]['iResponseCode'] ?? 302),
    );
}

/*
 * 403
 */
\MVC\Route::any(
    sPath: '/403/',
    sClassMethod: '\{module}\Controller\Index::forbidden',
    mOptional: clone $oDTRoutingAdditional->set_sTitle('403 - Forbidden')->set_sTemplate('Frontend/content/403.tpl'),
    sTag: '403',
);

/*
 * 404
 */
\MVC\Route::any(
    sPath: '/404/',
    sClassMethod: '\{module}\Controller\Index::notFound',
    mOptional: clone $oDTRoutingAdditional->set_sTitle('404 - Not Found')->set_sTemplate('Frontend/content/404.tpl'),
    sTag: '404',
);

/*
 * 410
 */
$aGone = array(
    '/gone/',
);

foreach ($aGone as $sGone)
{
    \MVC\Route::any(
        sPath: $sGone,
        sClassMethod: '\{module}\Controller\Index::gone',
        mOptional: clone $oDTRoutingAdditional->set_sTitle('410 - Gone')->set_sTemplate('Frontend/content/410.tpl'),
        sTag: '410',
    );
}