<?php

# List of Emvicy Standard Events
# @see https://emvicy.com/1.x/events#EmvicyStandardEvents


\MVC\Event::processBindConfigStack([

    'mvc.cron.executeTask.after' => [
        function(\MVC\DataType\DTCronTask $oDTCronTask) {
            \MVC\Log::write(
                $oDTCronTask->get_iPid() . "\t" . $oDTCronTask->get_sRoute() . "\t" . $oDTCronTask->get_iIntervall(),
                \MVC\Config::get_MVC_LOG_FILE_CRON()
            );
        },
    ],

    /**
     * @warning Be careful if listening to this; it would mean a huge amount of continuous data flow
     *          strictly recommended for development environment only
     */
//    'mvc.cron.executeTask.before' => [
//        function(\MVC\DataType\DTCronTask $oDTCronTask) {
//            \MVC\Log::write($oDTCronTask->getPropertyJson(), \MVC\Config::get_MVC_LOG_FILE_CRON());
//        },
//    ],
    /**
     * @warning Be careful if listening to this; it would mean a huge amount of continuous data flow
     *          strictly recommended for development environment only
     */
//    'mvc.cron.executeTask.skip' => [
//        function(\MVC\DataType\DTCronTask $oDTCronTask) {
//            \MVC\Log::write('Skip - ' . $oDTCronTask->getPropertyJson(), \MVC\Config::get_MVC_LOG_FILE_CRON());
//        },
//    ],
]);