<?php

# List of Emvicy Standard Events
# @see https://mymvc.ueffing.net/3.4.x/events#EmvicyStandardEvents


\MVC\Event::processBindConfigStack([

    'db.model.db.create.before' => [
        /*
         * add timestamps if missing
         */
        function(MVC\DB\DataType\DB\TableDataType $oTableDataType) {

            (true === empty($oTableDataType->get_stampCreate())) ? $oTableDataType->set_stampCreate(date('Y-m-d H:i:s')) : false;
            (true === empty($oTableDataType->get_stampChange())) ? $oTableDataType->set_stampChange(date('Y-m-d H:i:s')) : false;
        },
    ],
    'db.model.db.update.before' => [
        /*
         * add timestamps if missing
         */
        function(MVC\DB\DataType\DB\TableDataType $oTableDataType) {

            (true === empty($oTableDataType->get_stampCreate())) ? $oTableDataType->set_stampCreate(date('Y-m-d H:i:s')) : false;
            (true === empty($oTableDataType->get_stampChange())) ? $oTableDataType->set_stampChange(date('Y-m-d H:i:s')) : false;
        },
    ],
    'mvc.db.model.db.construct.saveCache' => [
        /*
         * let create an openapi yaml file according to DB Table DataType Classes when the DataBase Tables setup changes
         */
        function() {
            // one-timer
            if (false === \MVC\Registry::isRegistered('DB::openapi'))
            {
                \MVC\Registry::set('DB::openapi', true);
                // generate /modules/{MODULE}/DataType/DTTables.yaml
                $sYamlFile = \MVC\DB\Model\Openapi::createDTYamlOnDTClasses(
                // pass instance of your concrete DB Class
                    \{MODULE}\Model\DB::init()
                );
            }
        },
    ],
]);

\MVC\Event::processBindConfigStack([

    'DT{module}ModelTableUser.set_password.before' => [
        /*
         * encrypt the transferred password
         */
        function(\MVC\DataType\DTValue $oDTValue){
            $oDTValue->set_mValue(
                password_hash(
                    $oDTValue->get_mValue(),
                    PASSWORD_DEFAULT
                )
            );
        },
    ],
]);

/*
 * log SQL Statements, if enabled via config
 */
if (true === \MVC\Config::get_MVC_LOG_SQL())
{
    \MVC\Event::processBindConfigStack([
        'db.model.db.create.sql' => array(function(\MVC\DataType\DTArrayObject $oDTArrayObject) {\MVC\Log::write($oDTArrayObject->getDTKeyValueByKey('sSql')->get_sValue(), \MVC\Config::get_MVC_LOG_FILE_SQL());}),
        'db.model.db.insert.sql' => array(function(\MVC\DataType\DTArrayObject $oDTArrayObject) {\MVC\Log::write($oDTArrayObject->getDTKeyValueByKey('sSql')->get_sValue(), \MVC\Config::get_MVC_LOG_FILE_SQL());}),
        'db.model.db.retrieve.sql' => array(function(\MVC\DataType\DTArrayObject $oDTArrayObject) {\MVC\Log::write($oDTArrayObject->getDTKeyValueByKey('sSql')->get_sValue(), \MVC\Config::get_MVC_LOG_FILE_SQL());}),
        'db.model.db.update.sql' => array(function(\MVC\DataType\DTArrayObject $oDTArrayObject) {\MVC\Log::write($oDTArrayObject->getDTKeyValueByKey('sSql')->get_sValue(), \MVC\Config::get_MVC_LOG_FILE_SQL());}),
        'db.model.db.delete.sql' => array(function(\MVC\DataType\DTArrayObject $oDTArrayObject) {\MVC\Log::write($oDTArrayObject->getDTKeyValueByKey('sSql')->get_sValue(), \MVC\Config::get_MVC_LOG_FILE_SQL());}),
        'db.model.db.createTable.sql' => array(function(\MVC\DataType\DTArrayObject $oDTArrayObject) {\MVC\Log::write($oDTArrayObject->getDTKeyValueByKey('sSql')->get_sValue(), \MVC\Config::get_MVC_LOG_FILE_SQL());}),
    ]);
}