<?php

# List of Emvicy Standard Events
# @see https://emvicy.com/1.x/events#EmvicyStandardEvents


\MVC\Event::processBindConfigStack([

    /**
     * on Input (PUT, POST, etc.)
     */
    'DTRequestCurrent.set_input.before' => [

        /**
         * sanitize input
         * following asset filter rules
         */
        function(\MVC\DataType\DTValue $oDTValue) {

            // detect incoming type of input
            $sTypeIncoming = gettype($oDTValue->get_mValue());

            // we need array...
            ('string' === $sTypeIncoming)
                ? parse_str($oDTValue->get_mValue(), $aInput)
                : $aInput = $oDTValue->get_mValue()
            ;

            foreach ($aInput as $sKey => $sInput)
            {
                $aSet = \MVC\Asset::init()->get('Filter.Request.input.' . $sKey);

                if (true === empty($aSet))
                {
                    continue;
                }

                // sanitize_var
                foreach (get($aSet['sanitize_var'], []) as $iSanitizeVar)
                {
                    $aInput[$sKey] = filter_var($aInput[$sKey], $iSanitizeVar);
                }

                // preg_replace
                foreach (get($aSet['preg_replace'], []) as $sRegEx)
                {
                    $aInput[$sKey] = preg_replace($sRegEx, '', $aInput[$sKey]);
                }

                // cast
                $sCast = get($aSet['cast']);
                ('int' === $sCast) ? $aInput[$sKey] = (int) $aInput[$sKey] : false;
                ('string' === $sCast) ? $aInput[$sKey] = (string) $aInput[$sKey] : false;
                ('bool' === $sCast) ? $aInput[$sKey] = (boolean) $aInput[$sKey] : false;
                ('float' === $sCast) ? $aInput[$sKey] = (float) $aInput[$sKey] : false;
                ('array' === $sCast) ? $aInput[$sKey] = (array) $aInput[$sKey] : false;
            }

            // ...if incoming type was string, convert back
            ('string' === $sTypeIncoming) ? $aInput = http_build_query($aInput) : false;

            $oDTValue->set_mValue($aInput);
        },
    ],
]);
