<?php

# List of Emvicy Standard Events
# @see https://emvicy.com/1.x/events#EmvicyStandardEvents


\MVC\Event::processBindConfigStack([

//    'mvc.event.init.after' => [
//        /**
//         * at this early stage
//         * create "Assets" object with given config
//         */
//        function(){
//            \MVC\Asset::init(\MVC\Config::get_MVC_MODULE_PRIMARY_STAGING_CONFIG_DIR() . '/_asset.yaml');
//        },
//    ],

    /**
     * after current request was get
     */
    'mvc.request.in.after' => [
        /*
         * logging requests
         */
        function(\MVC\DataType\DTRequestIn $oDTRequestIn, \MVC\DataType\DTEventContext $oDTEventContext) {

            if (false === \MVC\Config::get_MVC_LOG_REQUEST())
            {
                return false;
            }

            \MVC\Log::write(php_sapi_name () . ' ' . $oDTRequestIn->get_requestMethod() . ' ' . $oDTRequestIn->get_path(), \MVC\Config::get_MVC_LOG_FILE_REQUEST());
        },
    ],
]);
